name:        Stuart Kent
description: Stuart Kent
url:         http://stkent.github.io
markdown:    kramdown
highligher:  true
paginate:    5
comments:    true
kramdown:
  input: GFM
# sass:
#   style: :compressed

collections:
- apps
- presentations

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"
      layout: "post"