name:        Stuart Kent
markdown:    kramdown
highligher:  true
paginate:    5
description: Stuart Kent
kramdown:
  input: GFM

collections:
- apps
- presentations

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Stuart Kent"