name:              Stuart Kent
description:       Stuart Kent
url:               http://stkent.github.io
paginate:          5
comments:          true
excerpt_separator: "<!--more-->"

kramdown:
  hard_wrap: false

sass:
  style: :compressed

collections:
- apps
- libraries
- talks

gems: [jekyll-paginate]