name:        Stuart Kent
markdown:    kramdown
highligher:  true
paginate:    5
description: Stuart Kent
kramdown:
  input: GFM
gems:
  - jekyll-mentions
# sass:
#   style: :compressed

collections:
- apps
- presentations
