name:        Stuart Kent
markdown:    redcarpet
highligher:  true
paginate:    8
description: Stuart Kent | Android Developer @ Detroit Labs

owner:
  name:           Stuart Kent
  twitter:       skentphd
  github:        stkent
