name:              Stuart Kent on Software
description:       Blog posts and projects, focused on Android and iOS apps.
url:               http://www.stkent.com
paginate:          5
comments:          true
excerpt_separator: "<!--more-->"

kramdown:
  hard_wrap: false

# sass:
#   style: :compressed

collections:
- apps
- libraries
- talks

gems: [jekyll-paginate]

jquery_version: "2.2.4"
