name:        Stuart Kent
markdown:    redcarpet
highligher:  true
paginate:    5
description: Stuart Kent
kramdown:
  input: GFM
# sass:
#   style: :compressed

collections:
- apps
- presentations

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Stuart Kent"