# Build

plugins:
  - jekyll-gist

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

markdown: kramdown
kramdown:
  hard_wrap: false

sass:
  style: :compressed

# Site

title:            Stuart Kent on Android
feed_description: An Android Dev's Perspectives
url:              http://www.stkent.com
baseurl:          ""

# Author

twitter_username:       skentphd
github_username:        stkent
stack_overflow_user_id: 2911458

# Content

excerpt_separator: <!--more-->

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      comments: true