name:        Stuart Kent
markdown:    kramdown
highligher:  true
paginate:    5
description: Stuart Kent
comments:    true
kramdown:
  input: GFM
# sass:
#   style: :compressed

collections:
- apps
- presentations

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"
      layout: "post"