# Build

gems:
  - jekyll-paginate

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

markdown: kramdown
kramdown:
  hard_wrap: false

sass:
  style: :compressed

# Site

title:       Stuart Kent on Software
description: Blog posts and projects, focused on Android and iOS apps.
url:         http://www.stkent.com
baseurl:     ""

# Author

twitter_username:       skentphd
github_username:        stkent
stack_overflow_user_id: 2911458

# Content

paginate:          5
comments:          true
excerpt_separator: <!--more-->

collections:
  - apps
  - libraries
  - talks
