name:        Stuart Kent
markdown:    redcarpet
highligher:  true
paginate:    5
description: Stuart Kent | Android Developer @ Detroit Labs

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Stuart Kent"